# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'GraphqlSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GraphqlSample
  pod "Apollo"

  target 'GraphqlSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GraphqlSampleUITests' do
    # Pods for testing
  end

end
